theme = "catppuccin_frappe"

[editor]
line-number = "relative"
shell = ["sh", "-c"]
continue-comments = false
completion-timeout = 5
completion-replace = true
bufferline = "multiple"
color-modes = true

[editor.lsp]
display-progress-messages = true
display-inlay-hints = true

[editor.auto-save]
after-delay.enable = true

[editor.indent-guides]
render = true

[editor.inline-diagnostics]
cursor-line = "error"

[keys.normal]
"A-c"= ":open ~/Documents/code"
"A-t"= ":run-shell-command alacritty"
"C-R"= ":config-reload"
